<table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                
    <td height="77" colspan="2" valign="bottom" align="right"><a href="../"><img src="../images/head_2.jpg" width="732" height="75" border="0"></a></td>
                
    <td width="10"><img src="../images/spacer.gif" width="1" height="1"></td>
                
    <td valign="bottom" align="center"> 
      <table width="80%" border="0" cellspacing="0" cellpadding="0">
                    <tr> 
                      
          <td align="center" width="50%"><a href="../"><img src="../images/home_inactive.gif" width="11" height="10" border="0"></a></td>
                      
          <td width="50%" align="center"><img src="../images/mail.gif" width="12" height="8"></td>
                    </tr>
                  </table>
                
      <br>
      <div class="qustion"> <a href="../qwe/">Задать вопрос косметологу</a></div>
    </td>
              </tr>
              <tr> 
                <td height="54" colspan="2" valign="bottom"> 
                  <table width="100%" border="0" cellspacing="0" cellpadding="3" align="right">
                    <tr> 
                      <td width="25%" align="left"><font color="#486280"><b><a href="/">На главную</a></b></font></td>
                      
          <td width="33%" align="center"><font color="#486280"><b><a href="../catalog/">Каталог 
            продукции</a></b></font></td>
                      
          <td align="center"><font color="#486280"><b><a href="../company/">О 
            компании</a></b></font></td>
                      
          <td align="right"><font color="#486280"><b><a href="../zakaz/">Как заказать?</a></b></font></td>
                    </tr>
                  </table>
                </td>
                
    <td height="34" width="10" ><img src="../images/spacer.gif" width="1" height="1"></td>
                <td height="34" valign="bottom"> 
                  <table width="100%" border="0" cellspacing="0" cellpadding="3">
                    <tr> 
                      
          <td width="62"></td>
                      
          <td width="170" align="right"><a href="http://si-ultra.biz/rass/"><b>Рассылка</b></a></td>
                    </tr>
                  </table>
                </td>
              </tr>
              <tr> 
                
    <td colspan="2" align="right"><img src="../images/top.jpg" width="732" height="263"></td>
                
    <td width="10"><img src="../images/spacer.gif" width="1" height="1"></td>
                
    <td align="right"> <? include  ($_SERVER[DOCUMENT_ROOT].'/top_prav.html'); ?></td>
              </tr>
            </table>
          
