<tr> 
    <td height="54" colspan="2" valign="bottom"> 
      <table width="100%" border="0" cellspacing="0" cellpadding="3" align="center">
        <tr> 
          <td width="25%" align="left"><font color="#486280"><b><a href="/">О 
            компании</a></b></font></td>
          <td width="33%" align="center"><font color="#486280"><b><a href="5.html">Каталог 
            продукции</a></b></font></td>
          <td align="center"><font color="#486280"><b><a href="#">Партнерство</a></b></font></td>
          <td align="right"><font color="#486280"><b><a href="#">Как заказать?</a></b></font></td>
        </tr>
      </table>
    </td>
    
  <td height="34" width="10" ><img src="../images/spacer.gif" width="1" height="1"></td>
    <td height="34" valign="bottom"> 
      <table width="100%" border="0" cellspacing="0" cellpadding="3">
        <tr> 
          <td width="62"><font color="#486280"><b> &nbsp;&nbsp;<a href="#">Форум</a></b></font></td>
          <td width="170">&nbsp;</td>
        </tr>
      </table>
    </td>
  </tr>
