
      <TABLE 
      style="BORDER-RIGHT: #ffffff 5px solid; BORDER-TOP: medium none; BORDER-LEFT: medium none; WIDTH: 100%; BORDER-BOTTOM: medium none" 
      cellSpacing=0 cellPadding=0>
        <TBODY>
        <TR>
          <TD 
          style="BORDER-RIGHT: #ffffff 5px solid; WIDTH: 30px; HEIGHT: 27px; BACKGROUND-COLOR: #458DD1"><IMG 
            style="WIDTH: 5px" 
            src="images/filler.gif"></TD>
          <TD 
          style="PADDING-LEFT: 7px; WIDTH: 100%; HEIGHT: 27px; BACKGROUND-COLOR: #458DD1"><font color="#FFFFFF" face="Arial, Helvetica, sans-serif">Лидер 
            продаж</font></TD>
          <TD 
            style="WIDTH: 100%; HEIGHT: 27px; BACKGROUND-COLOR: #458DD1">&nbsp;</TD>
        </TR>
        <TR>
          <TD 
            style="BORDER-RIGHT: #ffffff 5px solid; WIDTH: 30px; HEIGHT: 27px"><IMG 
            style="WIDTH: 5px" 
            src="images/filler.gif"></TD>
          <TD style="PADDING-TOP: 10px" colSpan=2>
            <TABLE style="WIDTH: 100%" cellSpacing=0 cellPadding=0>
              <TBODY>
              <TR>
                <TD style="VERTICAL-ALIGN: top; WIDTH: 5%" height="156"><IMG 
                  style="BORDER-RIGHT: #646a60 1px solid; BORDER-TOP: #646a60 1px solid; BORDER-LEFT: #646a60 1px solid; BORDER-BOTTOM: #646a60 1px solid" 
                  alt="" 
                  src="VitaActiva - натуральная израильская косметика.files/picture.jpg" 
                  width=80> </TD>
                <TD style="WIDTH: 10px" height="156">&nbsp;</TD>
                <TD style="VERTICAL-ALIGN: top; TEXT-ALIGN: right" height="156"><a href="#">Ампулированная 
                  косметика</a> 
                  <p> «Салон красоты для чувствительной кожи»<br>
                    <SPAN class=subhdr 
                  style="PADDING-RIGHT: 0px; PADDING-LEFT: 0px; PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-TOP: 0px; BACKGROUND-COLOR: #e1f1fa">&nbsp;</SPAN><SPAN class=subhdr 
                  style="BACKGROUND-COLOR: #daf2ec">(8 ампул по 2 мл) &nbsp;</SPAN> 
                  </p>
                  </TD>
              </TR></TBODY></TABLE></TD></TR></TBODY></TABLE><BR><BR>
      <TABLE 
      style="BORDER-RIGHT: #ffffff 5px solid; BORDER-TOP: medium none; BORDER-LEFT: medium none; WIDTH: 100%; BORDER-BOTTOM: medium none" 
      cellSpacing=0 cellPadding=0>
        <TBODY>
        <TR>
          <TD 
          style="BORDER-RIGHT: #ffffff 5px solid; WIDTH: 30px; HEIGHT: 27px; BACKGROUND-COLOR: #458DD1"><IMG 
            style="WIDTH: 5px" 
            src="images/filler.gif"></TD>
          <TD class=pghdr 
          style="PADDING-LEFT: 7px; WIDTH: 100%; HEIGHT: 27px; BACKGROUND-COLOR: #458DD1"><font color="#FFFFFF" face="Arial, Helvetica, sans-serif">Новинка</font></TD>
          <TD 
            style="WIDTH: 100%; HEIGHT: 27px; BACKGROUND-COLOR: #458DD1">&nbsp;</TD>
        </TR>
        <TR>
          <TD 
            style="BORDER-RIGHT: #ffffff 5px solid; WIDTH: 30px; HEIGHT: 27px"><IMG 
            style="WIDTH: 5px" 
            src="images/filler.gif"></TD>
          <TD style="PADDING-TOP: 10px" colSpan=2>
            <TABLE style="WIDTH: 100%" cellSpacing=0 cellPadding=0>
              <TBODY> 
              <TR> 
                <TD style="VERTICAL-ALIGN: top; WIDTH: 5%"><IMG 
                  style="BORDER-RIGHT: #646a60 1px solid; BORDER-TOP: #646a60 1px solid; BORDER-LEFT: #646a60 1px solid; BORDER-BOTTOM: #646a60 1px solid" 
                  alt="" 
                  src="baikal/53s.gif" 
                  width=80 height="164"> </TD>
                <TD style="WIDTH: 10px">&nbsp;</TD>
                <TD style="VERTICAL-ALIGN: top; TEXT-ALIGN: right"><a href="#">Бальзам 
                  для тела «Байкальский целитель» </a> 
                  <TABLE style="WIDTH: 100%" cellSpacing=0 cellPadding=0>
                    <TBODY> 
                    <TR> 
                      <TD 
                      style="WIDTH: 50%; PADDING-TOP: 10px; TEXT-ALIGN: center">&nbsp;</TD>
                      <TD 
                        style="VERTICAL-ALIGN: top; TEXT-ALIGN: right"><a href="#"><BR>
                        <SPAN 
                        class=subhdr 
                        style="PADDING-RIGHT: 0px; PADDING-LEFT: 0px; PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-TOP: 0px; BACKGROUND-COLOR: #e1f1fa">&nbsp;531 
                        руб.&nbsp;</SPAN><BR>
                        <SPAN class=subhdr 
                        style="BACKGROUND-COLOR: #daf2ec">&nbsp;200 мл&nbsp;</SPAN> 
                        </a></TD>
                    </TR>
                    </TBODY> 
                  </TABLE>
                </TD>
              </TR>
              </TBODY>
            </TABLE>
            <BR></TD></TR></TBODY></TABLE><BR><BR>
      <TABLE 
      style="BORDER-RIGHT: #ffffff 5px solid; BORDER-TOP: medium none; BORDER-LEFT: medium none; WIDTH: 100%; BORDER-BOTTOM: medium none" 
      cellSpacing=0 cellPadding=0>
        <TBODY> 
        <TR> 
          <TD 
          style="BORDER-RIGHT: #ffffff 5px solid; WIDTH: 30px; HEIGHT: 27px; BACKGROUND-COLOR: #458DD1"><IMG 
            style="WIDTH: 5px" 
            src="images/filler.gif"></TD>
          <TD class=pghdr 
          style="PADDING-LEFT: 7px; WIDTH: 100%; HEIGHT: 27px; BACKGROUND-COLOR: #458DD1"><font color="#FFFFFF" face="Arial, Helvetica, sans-serif">Рассылка 
            &quot;Лечебная косметика&quot;</font></TD>
        </TR>
        <TR> 
          <TD 
            style="BORDER-RIGHT: #ffffff 5px solid; WIDTH: 30px; HEIGHT: 27px"><IMG 
            style="WIDTH: 5px" 
            src="images/filler.gif"></TD>
          <TD style="PADDING-TOP: 10px"> 
            <TABLE style="WIDTH: 100%" cellSpacing=0 cellPadding=0>
              <TBODY> 
              <TR> 
                <TD style="VERTICAL-ALIGN: top"> 
                  <DIV 
                  style="PADDING-BOTTOM: 5px; VERTICAL-ALIGN: bottom; BORDER-BOTTOM: #646a60 1px dotted; HEIGHT: 20px"><a href="#"><SPAN 
                  class=date>25.04.2007</SPAN>&nbsp;&nbsp;</a></DIV>
                  <DIV class=txt 
                  style="PADDING-RIGHT: 7px; PADDING-TOP: 2px"><a href="#">Продажа 
                    в интернет-магазине kosmetikalux</a></DIV>
                  <DIV style="PADDING-RIGHT: 7px; PADDING-TOP: 7px"><a href="#">С 
                    радостью извещаем Вас о том, что теперь Вы сможе...</a></DIV>
                </TD>
                <TD 
                style="PADDING-RIGHT: 0px; PADDING-LEFT: 0px; PADDING-BOTTOM: 0px; VERTICAL-ALIGN: top; WIDTH: 5%; PADDING-TOP: 0px"> 
                  <DIV 
                  style="BORDER-RIGHT: #646a60 1px dotted; BORDER-TOP: #646a60 1px dotted; BORDER-LEFT: #646a60 1px dotted; BORDER-BOTTOM: #646a60 1px dotted"><IMG 
                  style="MARGIN: 3px" 
                  src="VitaActiva - натуральная израильская косметика.files/15.jpg" 
                  width=80><BR>
                  </DIV>
                </TD>
              </TR>
              <TR> 
                <TD style="HEIGHT: 20px" colSpan=2><IMG height=1 src="" 
                  width=10></TD>
              </TR>
              </TBODY> 
            </TABLE>
          </TD>
        </TR>
        </TBODY> 
      </TABLE>

    